#!/bin/bash
PATH="/usr/bin:$PATH"
ID="$USERNAME@$USERDOMAIN;$USERPROFILE;$(cygpath -w /)"
IDF=/portable-cygwin/session-id
if [ "$ID" != "$(cat "$IDF")" ]; then
echo - > "$IDF"
echo writing /etc/passwd
mkpasswd -l -c | sed -r 's/^(.*\:)[^:]*(\:[^:]*)$/\1\/home\2/' > /etc/passwd || ID=-
echo writing /etc/group
mkgroup -l -c > /etc/group || ID=-
echo setting up special paths in background
(/portable-cygwin/setup-special-paths && echo "$ID" > "$IDF";) &
fi
