#!/bin/bash
PATH="/usr/bin:$PATH"
ID="$USERNAME@$USERDOMAIN;$USERPROFILE;$(cygpath -w /)"
IDF=/portable-cygwin/session-id
if [ "$ID" != "$(cat "$IDF")" ]; then
echo - > "$IDF"
echo writing /etc/passwd
mkpasswd -l -c | sed -r 's/^(.*\:)[^:]*(\:[^:]*)$/\1\/home\2/' > /etc/passwd || ID=-
echo writing /etc/group
mkgroup -l -c > /etc/group || ID=-
echo setting up special paths in background
(
l=/sf
rm -rf $l /parent
ln -s "$(cygpath -u "$(dirname "$(cygpath -w /)")")" /parent
mkdir -p $l
cd $l
cat /portable-cygwin/special-paths |
while read a b; do
t="$(cygpath -F $a)"
[ "$(echo "$t"|grep -Fc /)" == 1 -a '!' -e "$4" ] && ln -s "$t" "$b"
done 2> /dev/null
echo "$ID" > "$IDF"
) &
fi
